### ISSUE TITLE
[FR] Remove dependency on `dbus`

### ISSUE THREAD

**Issue by xplshn** [System64fumo/frog#1]
Hi, I built `frog`, after changing `uint` to `unsigned int` in the source code, to be able to build.

Once I built the executable, I encountered this:
![image](https://github.com/user-attachments/assets/4b2f9b67-dbec-4d8e-a68d-a6be67ec7f78)

I don't have dbus on my system, and don't intend to have it either. Can I somehow work around this?

I tried with a sandbox (noroot-do, of the xplshn/a-utils project), and I've dbus-run-session within it, but no system dbus daemon is running, so it is kind of a stub (tho it has allowed me to run some programs that throw a tantrum when dbus is not there). 
![image](https://github.com/user-attachments/assets/352bab79-b05c-4c88-97b6-f25b8a57af79)

**Comment by System64fumo** [comment]
Humm quite an odd case, I don't think i use dbus for anything in frog anymore?
Try removing line 10 in include/disk.hpp see what happens?

**Comment by xplshn** [comment]
It didn't help, I think GTK itself requires and links with dbus :(
